### ISSUE TITLE
Viera ears gone + ability to point to your own character preset when changing races

### ISSUE THREAD

**Issue by frukbachers** [Fr4nsson/MyDalamudPlugins#2]
I decided to try out your repository for the ability to change your own race. Morality aside, when changing to viera, ears disappeared completely.

Maybe there is a way to point the plugin to your own character presets per race / sex to prevent this from happening? 

Quick reply would be appreciated.

**Comment by frukbachers** [comment]
Is there gonna be feedback on this?

**Comment by Fr4nsson** [comment]
I don't put a lot of time on these kinds of plugins so this is nothing I'm planning to fix right now. I'd recommend you take a look at [Glamourer](https://github.com/Ottermandias/Glamourer/tree/main/Glamourer) instead if you just want to change your race.
