### ISSUE TITLE
Needs updating to 6.1 

### ISSUE THREAD

**Issue by dafunks** [Fr4nsson/MyDalamudPlugins#3]
Plugins showing as outdated and incompatible

**Comment by seathasky** [comment]
Any update on this? Developer inactive it seems.

**Comment by frukbachers** [comment]
Would like to see this updated as well. There were a number of plugins but ever since new API came out, all of them are gone, even the All Lalafells plugin

would just like to play the game without this shit race in it.

**Comment by seathasky** [comment]
I see a lot of Dalamud plugin devs do this though...make a cool plugin and then never update it ever again probably because they stopped playing the game. It's a shame. Hopefully someone forks this release.

**Comment by seathasky** [comment]
**Edit:** Looks like author merged my PR, shouldn't need to do these steps anymore.

If anyone trying to get it working, here's a quick bandaid fix for 6.1.

go to:

**C:\Users\YOURUSERNAME\AppData\Roaming\XIVLauncher** directory and into the **"Installedplugins"** folder.
Find **HidePadlock** folder and move it out of **"installedPlugins"** and into **"devplugins"** folder in the **XIVlauncher** folder.

After you have done that, open the **Hidepadlock** folder and open the **HidePadlock.json** file with a text editor and change this line:
**"DalamudApiLevel": 5,** to **"DalamudApiLevel": 6,**

![image](https://user-images.githubusercontent.com/17598024/165193928-3b12edd5-50ba-4fbf-bbec-d9f86f0b0832.png)

![image](https://user-images.githubusercontent.com/17598024/165193967-37ae419b-2035-4758-9bf5-b628bd9cce5e.png)

You can verify it working as Dev Tools will be added to your plugins list in game similar to this:
![image](https://user-images.githubusercontent.com/17598024/165194467-4b52899c-fdf8-46a3-ba11-ce14012a826d.png)

**Comment by Dedoooo** [comment]
will oopsnolalafell ever be updated? 😞

**Comment by Fr4nsson** [comment]
> will oopsnolalafell ever be updated? 😞

Maybe sometime in the future, I have no plans for it atm.
